var $ = require('jquery');



//Search Player:

var playerSearch = 'luka';
var url = `https://www.balldontlie.io/api/v1/players?search=${playerSearch}`

$.ajax({
  url: url,
  type: 'GET',
})




{
  "data": [
      {
          "id": 1820647,
          "ast": 4,
          "blk": 0,
          "dreb": 3,
          "fg3_pct": 16.7,
          "fg3a": 6,
          "fg3m": 1,
          "fg_pct": 31.6,
          "fga": 19,
          "fgm": 6,
          "ft_pct": 100.0,
          "fta": 2,
          "ftm": 2,
          "game": {
              "id": 63118,
              "date": "2020-01-05T00:00:00.000Z",
              "home_team_id": 6,
              "home_team_score": 103,
              "period": 4,
              "postseason": false,
              "season": 2019,
              "status": "Final",
              "time": "     ",
              "visitor_team_id": 18,
              "visitor_team_score": 118
          },
          "min": "30:53",
          "oreb": 4,
          "pf": 2,
          "player": {
              "id": 475,
              "first_name": "Andrew",
              "height_feet": 6,
              "height_inches": 8,
              "last_name": "Wiggins",
              "position": "F-G",
              "team_id": 18,
              "weight_pounds": 194
          },
          "pts": 15,
          "reb": 7,
          "stl": 2,
          "team": {
              "id": 18,
              "abbreviation": "MIN",
              "city": "Minnesota",
              "conference": "West",
              "division": "Northwest",
              "full_name": "Minnesota Timberwolves",
              "name": "Timberwolves"
          },
          "turnover": 3
      },
      {
          "id": 1820648,
          "ast": 2,
          "blk": 0,
          "dreb": 4,
          "fg3_pct": 40.0,
          "fg3a": 10,
          "fg3m": 4,
          "fg_pct": 38.5,
          "fga": 13,
          "fgm": 5,
          "ft_pct": 50.0,
          "fta": 2,
          "ftm": 1,
          "game": {
              "id": 63118,
              "date": "2020-01-05T00:00:00.000Z",
              "home_team_id": 6,
              "home_team_score": 103,
              "period": 4,
              "postseason": false,
              "season": 2019,
              "status": "Final",
              "time": "     ",
              "visitor_team_id": 18,
              "visitor_team_score": 118
          },
          "min": "33:50",
          "oreb": 0,
          "pf": 2,
          "player": {
              "id": 108,
              "first_name": "Robert",
              "height_feet": 6,
              "height_inches": 9,
              "last_name": "Covington",
              "position": "F",
              "team_id": 18,
              "weight_pounds": 225
          },
          "pts": 15,
          "reb": 4,
          "stl": 4,
          "team": {
              "id": 18,
              "abbreviation": "MIN",
              "city": "Minnesota",
              "conference": "West",
              "division": "Northwest",
              "full_name": "Minnesota Timberwolves",
              "name": "Timberwolves"
          },
          "turnover": 1
      },
      {
          "id": 1820649,
          "ast": 6,
          "blk": 4,
          "dreb": 9,
          "fg3_pct": 80.0,
          "fg3a": 5,
          "fg3m": 4,
          "fg_pct": 80.0,
          "fga": 10,
          "fgm": 8,
          "ft_pct": 100.0,
          "fta": 2,
          "ftm": 2,
          "game": {
              "id": 63118,
              "date": "2020-01-05T00:00:00.000Z",
              "home_team_id": 6,
              "home_team_score": 103,
              "period": 4,
              "postseason": false,
              "season": 2019,
              "status": "Final",
              "time": "     ",
              "visitor_team_id": 18,
              "visitor_team_score": 118
          },
          "min": "29:16",
          "oreb": 4,
          "pf": 0,
          "player": {
              "id": 129,
              "first_name": "Gorgui",
              "height_feet": 6,
              "height_inches": 11,
              "last_name": "Dieng",
              "position": "C",
              "team_id": 18,
              "weight_pounds": 252
          },
          "pts": 22,
          "reb": 13,
          "stl": 0,
          "team": {
              "id": 18,
              "abbreviation": "MIN",
              "city": "Minnesota",
              "conference": "West",
              "division": "Northwest",
              "full_name": "Minnesota Timberwolves",
              "name": "Timberwolves"
          },
          "turnover": 2
      },
      {
          "id": 1820650,
          "ast": 3,
          "blk": 2,
          "dreb": 0,
          "fg3_pct": 50.0,
          "fg3a": 4,
          "fg3m": 2,
          "fg_pct": 54.5,
          "fga": 11,
          "fgm": 6,
          "ft_pct": 0.0,
          "fta": 1,
          "ftm": 0,
          "game": {
              "id": 63118,
              "date": "2020-01-05T00:00:00.000Z",
              "home_team_id": 6,
              "home_team_score": 103,
              "period": 4,
              "postseason": false,
              "season": 2019,
              "status": "Final",
              "time": "     ",
              "visitor_team_id": 18,
              "visitor_team_score": 118
          },
          "min": "28:08",
          "oreb": 3,
          "pf": 4,
          "player": {
              "id": 666523,
              "first_name": "Jarrett",
              "height_feet": null,
              "height_inches": null,
              "last_name": "Culver",
              "position": "G",
              "team_id": 18,
              "weight_pounds": null
          },
          "pts": 14,
          "reb": 3,
          "stl": 4,
          "team": {
              "id": 18,
              "abbreviation": "MIN",
              "city": "Minnesota",
              "conference": "West",
              "division": "Northwest",
              "full_name": "Minnesota Timberwolves",
              "name": "Timberwolves"
          },
          "turnover": 1
      },
      {
          "id": 1820651,
          "ast": 7,
          "blk": 0,
          "dreb": 1,
          "fg3_pct": 66.7,
          "fg3a": 3,
          "fg3m": 2,
          "fg_pct": 80.0,
          "fga": 10,
          "fgm": 8,
          "ft_pct": 100.0,
          "fta": 3,
          "ftm": 3,
          "game": {
              "id": 63118,
              "date": "2020-01-05T00:00:00.000Z",
              "home_team_id": 6,
              "home_team_score": 103,
              "period": 4,
              "postseason": false,
              "season": 2019,
              "status": "Final",
              "time": "     ",
              "visitor_team_id": 18,
              "visitor_team_score": 118
          },
          "min": "30:04",
          "oreb": 1,
          "pf": 2,
          "player": {
              "id": 341,
              "first_name": "Shabazz",
              "height_feet": 6,
              "height_inches": 1,
              "last_name": "Napier",
              "position": "G",
              "team_id": 18,
              "weight_pounds": 180
          },
          "pts": 21,
          "reb": 2,
          "stl": 1,
          "team": {
              "id": 18,
              "abbreviation": "MIN",
              "city": "Minnesota",
              "conference": "West",
              "division": "Northwest",
              "full_name": "Minnesota Timberwolves",
              "name": "Timberwolves"
          },
          "turnover": 1
      },
      {
          "id": 1820652,
          "ast": 5,
          "blk": 0,
          "dreb": 1,
          "fg3_pct": 0.0,
          "fg3a": 0,
          "fg3m": 0,
          "fg_pct": 66.7,
          "fga": 3,
          "fgm": 2,
          "ft_pct": 100.0,
          "fta": 1,
          "ftm": 1,
          "game": {
              "id": 63118,
              "date": "2020-01-05T00:00:00.000Z",
              "home_team_id": 6,
              "home_team_score": 103,
              "period": 4,
              "postseason": false,
              "season": 2019,
              "status": "Final",
              "time": "     ",
              "visitor_team_id": 18,
              "visitor_team_score": 118
          },
          "min": "17:09",
          "oreb": 0,
          "pf": 2,
          "player": {
              "id": 435,
              "first_name": "Jeff",
              "height_feet": 6,
              "height_inches": 2,
              "last_name": "Teague",
              "position": "G",
              "team_id": 18,
              "weight_pounds": 195
          },
          "pts": 5,
          "reb": 1,
          "stl": 1,
          "team": {
              "id": 18,
              "abbreviation": "MIN",
              "city": "Minnesota",
              "conference": "West",
              "division": "Northwest",
              "full_name": "Minnesota Timberwolves",
              "name": "Timberwolves"
          },
          "turnover": 1
      },
      {
          "id": 1820653,
          "ast": 0,
          "blk": 1,
          "dreb": 3,
          "fg3_pct": 0.0,
          "fg3a": 0,
          "fg3m": 0,
          "fg_pct": 66.7,
          "fga": 3,
          "fgm": 2,
          "ft_pct": 0.0,
          "fta": 0,
          "ftm": 0,
          "game": {
              "id": 63118,
              "date": "2020-01-05T00:00:00.000Z",
              "home_team_id": 6,
              "home_team_score": 103,
              "period": 4,
              "postseason": false,
              "season": 2019,
              "status": "Final",
              "time": "     ",
              "visitor_team_id": 18,
              "visitor_team_score": 118
          },
          "min": "7:54",
          "oreb": 0,
          "pf": 0,
          "player": {
              "id": 459,
              "first_name": "Noah",
              "height_feet": 6,
              "height_inches": 9,
              "last_name": "Vonleh",
              "position": "F",
              "team_id": 18,
              "weight_pounds": 250
          },
          "pts": 4,
          "reb": 3,
          "stl": 0,
          "team": {
              "id": 18,
              "abbreviation": "MIN",
              "city": "Minnesota",
              "conference": "West",
              "division": "Northwest",
              "full_name": "Minnesota Timberwolves",
              "name": "Timberwolves"
          },
          "turnover": 0
      },
      {
          "id": 1820658,
          "ast": 0,
          "blk": 0,
          "dreb": 0,
          "fg3_pct": 0.0,
          "fg3a": 0,
          "fg3m": 0,
          "fg_pct": 0.0,
          "fga": 0,
          "fgm": 0,
          "ft_pct": 0.0,
          "fta": 0,
          "ftm": 0,
          "game": {
              "id": 63118,
              "date": "2020-01-05T00:00:00.000Z",
              "home_team_id": 6,
              "home_team_score": 103,
              "period": 4,
              "postseason": false,
              "season": 2019,
              "status": "Final",
              "time": "     ",
              "visitor_team_id": 18,
              "visitor_team_score": 118
          },
          "min": "0:46",
          "oreb": 0,
          "pf": 0,
          "player": {
              "id": 41,
              "first_name": "Jordan",
              "height_feet": 6,
              "height_inches": 9,
              "last_name": "Bell",
              "position": "F",
              "team_id": 18,
              "weight_pounds": 224
          },
          "pts": 0,
          "reb": 0,
          "stl": 0,
          "team": {
              "id": 18,
              "abbreviation": "MIN",
              "city": "Minnesota",
              "conference": "West",
              "division": "Northwest",
              "full_name": "Minnesota Timberwolves",
              "name": "Timberwolves"
          },
          "turnover": 0
      },
      {
          "id": 1820659,
          "ast": 0,
          "blk": 0,
          "dreb": 0,
          "fg3_pct": 0.0,
          "fg3a": 0,
          "fg3m": 0,
          "fg_pct": 0.0,
          "fga": 0,
          "fgm": 0,
          "ft_pct": 0.0,
          "fta": 0,
          "ftm": 0,
          "game": {
              "id": 63118,
              "date": "2020-01-05T00:00:00.000Z",
              "home_team_id": 6,
              "home_team_score": 103,
              "period": 4,
              "postseason": false,
              "season": 2019,
              "status": "Final",
              "time": "     ",
              "visitor_team_id": 18,
              "visitor_team_score": 118
          },
          "min": "0:00",
          "oreb": 0,
          "pf": 0,
          "player": {
              "id": 181,
              "first_name": "Treveon",
              "height_feet": 6,
              "height_inches": 5,
              "last_name": "Graham",
              "position": "F",
              "team_id": 18,
              "weight_pounds": 225
          },
          "pts": 0,
          "reb": 0,
          "stl": 0,
          "team": {
              "id": 18,
              "abbreviation": "MIN",
              "city": "Minnesota",
              "conference": "West",
              "division": "Northwest",
              "full_name": "Minnesota Timberwolves",
              "name": "Timberwolves"
          },
          "turnover": 0
      },
      {
          "id": 1820660,
          "ast": 0,
          "blk": 0,
          "dreb": 4,
          "fg3_pct": 0.0,
          "fg3a": 0,
          "fg3m": 0,
          "fg_pct": 50.0,
          "fga": 6,
          "fgm": 3,
          "ft_pct": 0.0,
          "fta": 2,
          "ftm": 0,
          "game": {
              "id": 63118,
              "date": "2020-01-05T00:00:00.000Z",
              "home_team_id": 6,
              "home_team_score": 103,
              "period": 4,
              "postseason": false,
              "season": 2019,
              "status": "Final",
              "time": "     ",
              "visitor_team_id": 18,
              "visitor_team_score": 118
          },
          "min": "19:27",
          "oreb": 1,
          "pf": 1,
          "player": {
              "id": 666849,
              "first_name": "Kevin",
              "height_feet": null,
              "height_inches": null,
              "last_name": "Porter Jr.",
              "position": "G",
              "team_id": 6,
              "weight_pounds": null
          },
          "pts": 6,
          "reb": 5,
          "stl": 1,
          "team": {
              "id": 6,
              "abbreviation": "CLE",
              "city": "Cleveland",
              "conference": "East",
              "division": "Central",
              "full_name": "Cleveland Cavaliers",
              "name": "Cavaliers"
          },
          "turnover": 2
      },
      {
          "id": 1820661,
          "ast": 1,
          "blk": 1,
          "dreb": 2,
          "fg3_pct": 0.0,
          "fg3a": 3,
          "fg3m": 0,
          "fg_pct": 37.5,
          "fga": 8,
          "fgm": 3,
          "ft_pct": 100.0,
          "fta": 1,
          "ftm": 1,
          "game": {
              "id": 63118,
              "date": "2020-01-05T00:00:00.000Z",
              "home_team_id": 6,
              "home_team_score": 103,
              "period": 4,
              "postseason": false,
              "season": 2019,
              "status": "Final",
              "time": "     ",
              "visitor_team_id": 18,
              "visitor_team_score": 118
          },
          "min": "29:43",
          "oreb": 0,
          "pf": 2,
          "player": {
              "id": 359,
              "first_name": "Cedi",
              "height_feet": 6,
              "height_inches": 8,
              "last_name": "Osman",
              "position": "F",
              "team_id": 6,
              "weight_pounds": 215
          },
          "pts": 7,
          "reb": 2,
          "stl": 0,
          "team": {
              "id": 6,
              "abbreviation": "CLE",
              "city": "Cleveland",
              "conference": "East",
              "division": "Central",
              "full_name": "Cleveland Cavaliers",
              "name": "Cavaliers"
          },
          "turnover": 3
      },
      {
          "id": 1820662,
          "ast": 3,
          "blk": 1,
          "dreb": 6,
          "fg3_pct": 0.0,
          "fg3a": 1,
          "fg3m": 0,
          "fg_pct": 42.9,
          "fga": 7,
          "fgm": 3,
          "ft_pct": 100.0,
          "fta": 1,
          "ftm": 1,
          "game": {
              "id": 63118,
              "date": "2020-01-05T00:00:00.000Z",
              "home_team_id": 6,
              "home_team_score": 103,
              "period": 4,
              "postseason": false,
              "season": 2019,
              "status": "Final",
              "time": "     ",
              "visitor_team_id": 18,
              "visitor_team_score": 118
          },
          "min": "23:25",
          "oreb": 5,
          "pf": 1,
          "player": {
              "id": 205,
              "first_name": "John",
              "height_feet": 6,
              "height_inches": 11,
              "last_name": "Henson",
              "position": "F",
              "team_id": 6,
              "weight_pounds": 219
          },
          "pts": 7,
          "reb": 11,
          "stl": 0,
          "team": {
              "id": 6,
              "abbreviation": "CLE",
              "city": "Cleveland",
              "conference": "East",
              "division": "Central",
              "full_name": "Cleveland Cavaliers",
              "name": "Cavaliers"
          },
          "turnover": 1
      },
      {
          "id": 1820663,
          "ast": 2,
          "blk": 0,
          "dreb": 3,
          "fg3_pct": 25.0,
          "fg3a": 4,
          "fg3m": 1,
          "fg_pct": 41.2,
          "fga": 17,
          "fgm": 7,
          "ft_pct": 100.0,
          "fta": 4,
          "ftm": 4,
          "game": {
              "id": 63118,
              "date": "2020-01-05T00:00:00.000Z",
              "home_team_id": 6,
              "home_team_score": 103,
              "period": 4,
              "postseason": false,
              "season": 2019,
              "status": "Final",
              "time": "     ",
              "visitor_team_id": 18,
              "visitor_team_score": 118
          },
          "min": "35:28",
          "oreb": 0,
          "pf": 2,
          "player": {
              "id": 413,
              "first_name": "Collin",
              "height_feet": 6,
              "height_inches": 2,
              "last_name": "Sexton",
              "position": "G",
              "team_id": 6,
              "weight_pounds": 190
          },
          "pts": 19,
          "reb": 3,
          "stl": 2,
          "team": {
              "id": 6,
              "abbreviation": "CLE",
              "city": "Cleveland",
              "conference": "East",
              "division": "Central",
              "full_name": "Cleveland Cavaliers",
              "name": "Cavaliers"
          },
          "turnover": 3
      },
      {
          "id": 1820669,
          "ast": 3,
          "blk": 0,
          "dreb": 3,
          "fg3_pct": 16.7,
          "fg3a": 6,
          "fg3m": 1,
          "fg_pct": 25.0,
          "fga": 8,
          "fgm": 2,
          "ft_pct": 0.0,
          "fta": 1,
          "ftm": 0,
          "game": {
              "id": 63118,
              "date": "2020-01-05T00:00:00.000Z",
              "home_team_id": 6,
              "home_team_score": 103,
              "period": 4,
              "postseason": false,
              "season": 2019,
              "status": "Final",
              "time": "     ",
              "visitor_team_id": 18,
              "visitor_team_score": 118
          },
          "min": "23:00",
          "oreb": 1,
          "pf": 2,
          "player": {
              "id": 258,
              "first_name": "Brandon",
              "height_feet": 6,
              "height_inches": 3,
              "last_name": "Knight",
              "position": "G",
              "team_id": 6,
              "weight_pounds": 195
          },
          "pts": 5,
          "reb": 4,
          "stl": 1,
          "team": {
              "id": 6,
              "abbreviation": "CLE",
              "city": "Cleveland",
              "conference": "East",
              "division": "Central",
              "full_name": "Cleveland Cavaliers",
              "name": "Cavaliers"
          },
          "turnover": 2
      },
      {
          "id": 1820670,
          "ast": 0,
          "blk": 0,
          "dreb": 0,
          "fg3_pct": 0.0,
          "fg3a": 0,
          "fg3m": 0,
          "fg_pct": 0.0,
          "fga": 0,
          "fgm": 0,
          "ft_pct": 0.0,
          "fta": 0,
          "ftm": 0,
          "game": {
              "id": 63118,
              "date": "2020-01-05T00:00:00.000Z",
              "home_team_id": 6,
              "home_team_score": 103,
              "period": 4,
              "postseason": false,
              "season": 2019,
              "status": "Final",
              "time": "     ",
              "visitor_team_id": 18,
              "visitor_team_score": 118
          },
          "min": "0:00",
          "oreb": 0,
          "pf": 0,
          "player": {
              "id": 666517,
              "first_name": "Tyler",
              "height_feet": null,
              "height_inches": null,
              "last_name": "Cook",
              "position": "C",
              "team_id": 6,
              "weight_pounds": null
          },
          "pts": 0,
          "reb": 0,
          "stl": 0,
          "team": {
              "id": 6,
              "abbreviation": "CLE",
              "city": "Cleveland",
              "conference": "East",
              "division": "Central",
              "full_name": "Cleveland Cavaliers",
              "name": "Cavaliers"
          },
          "turnover": 0
      },
      {
          "id": 1820671,
          "ast": 0,
          "blk": 0,
          "dreb": 0,
          "fg3_pct": 0.0,
          "fg3a": 0,
          "fg3m": 0,
          "fg_pct": 0.0,
          "fga": 0,
          "fgm": 0,
          "ft_pct": 0.0,
          "fta": 0,
          "ftm": 0,
          "game": {
              "id": 63118,
              "date": "2020-01-05T00:00:00.000Z",
              "home_team_id": 6,
              "home_team_score": 103,
              "period": 4,
              "postseason": false,
              "season": 2019,
              "status": "Final",
              "time": "     ",
              "visitor_team_id": 18,
              "visitor_team_score": 118
          },
          "min": "0:00",
          "oreb": 0,
          "pf": 0,
          "player": {
              "id": 666940,
              "first_name": "Dean",
              "height_feet": null,
              "height_inches": null,
              "last_name": "Wade",
              "position": "F",
              "team_id": 6,
              "weight_pounds": null
          },
          "pts": 0,
          "reb": 0,
          "stl": 0,
          "team": {
              "id": 6,
              "abbreviation": "CLE",
              "city": "Cleveland",
              "conference": "East",
              "division": "Central",
              "full_name": "Cleveland Cavaliers",
              "name": "Cavaliers"
          },
          "turnover": 0
      },
      {
          "id": 1820657,
          "ast": 3,
          "blk": 0,
          "dreb": 1,
          "fg3_pct": 0.0,
          "fg3a": 1,
          "fg3m": 0,
          "fg_pct": 57.1,
          "fga": 7,
          "fgm": 4,
          "ft_pct": 0.0,
          "fta": 0,
          "ftm": 0,
          "game": {
              "id": 63118,
              "date": "2020-01-05T00:00:00.000Z",
              "home_team_id": 6,
              "home_team_score": 103,
              "period": 4,
              "postseason": false,
              "season": 2019,
              "status": "Final",
              "time": "     ",
              "visitor_team_id": 18,
              "visitor_team_score": 118
          },
          "min": "10:49",
          "oreb": 1,
          "pf": 2,
          "player": {
              "id": 667378,
              "first_name": "Naz",
              "height_feet": null,
              "height_inches": null,
              "last_name": "Reid",
              "position": "F-C",
              "team_id": 18,
              "weight_pounds": null
          },
          "pts": 8,
          "reb": 2,
          "stl": 3,
          "team": {
              "id": 18,
              "abbreviation": "MIN",
              "city": "Minnesota",
              "conference": "West",
              "division": "Northwest",
              "full_name": "Minnesota Timberwolves",
              "name": "Timberwolves"
          },
          "turnover": 2
      },
      {
          "id": 1820654,
          "ast": 1,
          "blk": 0,
          "dreb": 4,
          "fg3_pct": 0.0,
          "fg3a": 4,
          "fg3m": 0,
          "fg_pct": 33.3,
          "fga": 6,
          "fgm": 2,
          "ft_pct": 0.0,
          "fta": 0,
          "ftm": 0,
          "game": {
              "id": 63118,
              "date": "2020-01-05T00:00:00.000Z",
              "home_team_id": 6,
              "home_team_score": 103,
              "period": 4,
              "postseason": false,
              "season": 2019,
              "status": "Final",
              "time": "     ",
              "visitor_team_id": 18,
              "visitor_team_score": 118
          },
          "min": "17:17",
          "oreb": 1,
          "pf": 2,
          "player": {
              "id": 356,
              "first_name": "Josh",
              "height_feet": 6,
              "height_inches": 4,
              "last_name": "Okogie",
              "position": "G",
              "team_id": 18,
              "weight_pounds": 212
          },
          "pts": 4,
          "reb": 5,
          "stl": 1,
          "team": {
              "id": 18,
              "abbreviation": "MIN",
              "city": "Minnesota",
              "conference": "West",
              "division": "Northwest",
              "full_name": "Minnesota Timberwolves",
              "name": "Timberwolves"
          },
          "turnover": 3
      },
      {
          "id": 1820655,
          "ast": 1,
          "blk": 1,
          "dreb": 2,
          "fg3_pct": 25.0,
          "fg3a": 4,
          "fg3m": 1,
          "fg_pct": 40.0,
          "fga": 10,
          "fgm": 4,
          "ft_pct": 0.0,
          "fta": 0,
          "ftm": 0,
          "game": {
              "id": 63118,
              "date": "2020-01-05T00:00:00.000Z",
              "home_team_id": 6,
              "home_team_score": 103,
              "period": 4,
              "postseason": false,
              "season": 2019,
              "status": "Final",
              "time": "     ",
              "visitor_team_id": 18,
              "visitor_team_score": 118
          },
          "min": "19:41",
          "oreb": 0,
          "pf": 2,
          "player": {
              "id": 666751,
              "first_name": "Kelan",
              "height_feet": null,
              "height_inches": null,
              "last_name": "Martin",
              "position": "F",
              "team_id": 18,
              "weight_pounds": null
          },
          "pts": 9,
          "reb": 2,
          "stl": 0,
          "team": {
              "id": 18,
              "abbreviation": "MIN",
              "city": "Minnesota",
              "conference": "West",
              "division": "Northwest",
              "full_name": "Minnesota Timberwolves",
              "name": "Timberwolves"
          },
          "turnover": 0
      },
      {
          "id": 1820656,
          "ast": 0,
          "blk": 0,
          "dreb": 1,
          "fg3_pct": 0.0,
          "fg3a": 1,
          "fg3m": 0,
          "fg_pct": 0.0,
          "fga": 3,
          "fgm": 0,
          "ft_pct": 50.0,
          "fta": 2,
          "ftm": 1,
          "game": {
              "id": 63118,
              "date": "2020-01-05T00:00:00.000Z",
              "home_team_id": 6,
              "home_team_score": 103,
              "period": 4,
              "postseason": false,
              "season": 2019,
              "status": "Final",
              "time": "     ",
              "visitor_team_id": 18,
              "visitor_team_score": 118
          },
          "min": "14:09",
          "oreb": 0,
          "pf": 1,
          "player": {
              "id": 32,
              "first_name": "Keita",
              "height_feet": 6,
              "height_inches": 9,
              "last_name": "Bates-Diop",
              "position": "F",
              "team_id": 18,
              "weight_pounds": 229
          },
          "pts": 1,
          "reb": 1,
          "stl": 0,
          "team": {
              "id": 18,
              "abbreviation": "MIN",
              "city": "Minnesota",
              "conference": "West",
              "division": "Northwest",
              "full_name": "Minnesota Timberwolves",
              "name": "Timberwolves"
          },
          "turnover": 2
      },
      {
          "id": 1820667,
          "ast": 2,
          "blk": 0,
          "dreb": 3,
          "fg3_pct": 100.0,
          "fg3a": 4,
          "fg3m": 4,
          "fg_pct": 84.6,
          "fga": 13,
          "fgm": 11,
          "ft_pct": 100.0,
          "fta": 2,
          "ftm": 2,
          "game": {
              "id": 63118,
              "date": "2020-01-05T00:00:00.000Z",
              "home_team_id": 6,
              "home_team_score": 103,
              "period": 4,
              "postseason": false,
              "season": 2019,
              "status": "Final",
              "time": "     ",
              "visitor_team_id": 18,
              "visitor_team_score": 118
          },
          "min": "24:10",
          "oreb": 0,
          "pf": 1,
          "player": {
              "id": 151,
              "first_name": "Dante",
              "height_feet": 6,
              "height_inches": 6,
              "last_name": "Exum",
              "position": "G",
              "team_id": 6,
              "weight_pounds": 190
          },
          "pts": 28,
          "reb": 3,
          "stl": 1,
          "team": {
              "id": 6,
              "abbreviation": "CLE",
              "city": "Cleveland",
              "conference": "East",
              "division": "Central",
              "full_name": "Cleveland Cavaliers",
              "name": "Cavaliers"
          },
          "turnover": 3
      },
      {
          "id": 1820668,
          "ast": 0,
          "blk": 0,
          "dreb": 3,
          "fg3_pct": 0.0,
          "fg3a": 1,
          "fg3m": 0,
          "fg_pct": 20.0,
          "fga": 5,
          "fgm": 1,
          "ft_pct": 0.0,
          "fta": 0,
          "ftm": 0,
          "game": {
              "id": 63118,
              "date": "2020-01-05T00:00:00.000Z",
              "home_team_id": 6,
              "home_team_score": 103,
              "period": 4,
              "postseason": false,
              "season": 2019,
              "status": "Final",
              "time": "     ",
              "visitor_team_id": 18,
              "visitor_team_score": 118
          },
          "min": "21:05",
          "oreb": 1,
          "pf": 1,
          "player": {
              "id": 308,
              "first_name": "Alfonzo",
              "height_feet": 6,
              "height_inches": 8,
              "last_name": "McKinnie",
              "position": "F",
              "team_id": 6,
              "weight_pounds": 215
          },
          "pts": 2,
          "reb": 4,
          "stl": 0,
          "team": {
              "id": 6,
              "abbreviation": "CLE",
              "city": "Cleveland",
              "conference": "East",
              "division": "Central",
              "full_name": "Cleveland Cavaliers",
              "name": "Cavaliers"
          },
          "turnover": 1
      },
      {
          "id": 1820664,
          "ast": 2,
          "blk": 0,
          "dreb": 0,
          "fg3_pct": 40.0,
          "fg3a": 5,
          "fg3m": 2,
          "fg_pct": 33.3,
          "fga": 12,
          "fgm": 4,
          "ft_pct": 100.0,
          "fta": 4,
          "ftm": 4,
          "game": {
              "id": 63118,
              "date": "2020-01-05T00:00:00.000Z",
              "home_team_id": 6,
              "home_team_score": 103,
              "period": 4,
              "postseason": false,
              "season": 2019,
              "status": "Final",
              "time": "     ",
              "visitor_team_id": 18,
              "visitor_team_score": 118
          },
          "min": "35:19",
          "oreb": 0,
          "pf": 1,
          "player": {
              "id": 666581,
              "first_name": "Darius",
              "height_feet": null,
              "height_inches": null,
              "last_name": "Garland",
              "position": "G",
              "team_id": 6,
              "weight_pounds": null
          },
          "pts": 14,
          "reb": 0,
          "stl": 0,
          "team": {
              "id": 6,
              "abbreviation": "CLE",
              "city": "Cleveland",
              "conference": "East",
              "division": "Central",
              "full_name": "Cleveland Cavaliers",
              "name": "Cavaliers"
          },
          "turnover": 2
      },
      {
          "id": 1820665,
          "ast": 0,
          "blk": 0,
          "dreb": 0,
          "fg3_pct": 0.0,
          "fg3a": 1,
          "fg3m": 0,
          "fg_pct": 0.0,
          "fga": 1,
          "fgm": 0,
          "ft_pct": 0.0,
          "fta": 0,
          "ftm": 0,
          "game": {
              "id": 63118,
              "date": "2020-01-05T00:00:00.000Z",
              "home_team_id": 6,
              "home_team_score": 103,
              "period": 4,
              "postseason": false,
              "season": 2019,
              "status": "Final",
              "time": "     ",
              "visitor_team_id": 18,
              "visitor_team_score": 118
          },
          "min": "3:48",
          "oreb": 0,
          "pf": 0,
          "player": {
              "id": 123,
              "first_name": "Matthew",
              "height_feet": 6,
              "height_inches": 4,
              "last_name": "Dellavedova",
              "position": "G",
              "team_id": 6,
              "weight_pounds": 200
          },
          "pts": 0,
          "reb": 0,
          "stl": 0,
          "team": {
              "id": 6,
              "abbreviation": "CLE",
              "city": "Cleveland",
              "conference": "East",
              "division": "Central",
              "full_name": "Cleveland Cavaliers",
              "name": "Cavaliers"
          },
          "turnover": 0
      },
      {
          "id": 1820666,
          "ast": 2,
          "blk": 0,
          "dreb": 8,
          "fg3_pct": 0.0,
          "fg3a": 0,
          "fg3m": 0,
          "fg_pct": 85.7,
          "fga": 7,
          "fgm": 6,
          "ft_pct": 75.0,
          "fta": 4,
          "ftm": 3,
          "game": {
              "id": 63118,
              "date": "2020-01-05T00:00:00.000Z",
              "home_team_id": 6,
              "home_team_score": 103,
              "period": 4,
              "postseason": false,
              "season": 2019,
              "status": "Final",
              "time": "     ",
              "visitor_team_id": 18,
              "visitor_team_score": 118
          },
          "min": "24:35",
          "oreb": 4,
          "pf": 2,
          "player": {
              "id": 492,
              "first_name": "Ante",
              "height_feet": 6,
              "height_inches": 11,
              "last_name": "Zizic",
              "position": "C",
              "team_id": 6,
              "weight_pounds": 254
          },
          "pts": 15,
          "reb": 12,
          "stl": 1,
          "team": {
              "id": 6,
              "abbreviation": "CLE",
              "city": "Cleveland",
              "conference": "East",
              "division": "Central",
              "full_name": "Cleveland Cavaliers",
              "name": "Cavaliers"
          },
          "turnover": 3
      }
  ],
  "meta": {
      "total_pages": 6,
      "current_page": 1,
      "next_page": 2,
      "per_page": 25,
      "total_count": 126
  }
}